version: '3'
services:
    api:
        build: .
        ports:
            - '3001:3001'
        env_file:
            - .env.docker
        depends_on:
            - db
        command: >
            sh -c "pnpm migration:run && pnpm run start:prod"
    db:
        image: postgres:15-alpine
        ports:
            - 5431:5432
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD:-123123}
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_DB=${DB_NAME:-task_manager_full}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command:
volumes:
    postgres_data:
